name: Publish NeuroAI to PyPI

on:
  release:
    types: [published]

jobs:
  publish-neuroai:
    environment: testpypi_neuroai  # Must match your PyPI environment name
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Essential for OIDC
      contents: read

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: pip install setuptools wheel twine
      
    - name: Build package
      run: python setup.py sdist bdist_wheel
      
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/  # Remove for real PyPI
